name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/chat_frontend
            if [ ! -d "chat-frontend" ]; then
              git clone https://github.com/hamedor/chat_frontend.git chat-frontend
            else
              cd chat-frontend
            
              echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" > .env
              echo "VITE_WS_URL=${{ secrets.VITE_WS_URL }}" >> .env
              git pull
            fi
            cd chat-frontend
            npm install
            npm run build
            pm2 restart chat-frontend || pm2 start serve --name chat-frontend -- -s dist -l 3000